# Generated by Django 5.0.7 on 2024-08-05 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(default='default_img/blog.png', upload_to='blog_img', verbose_name='Изображение блога'),
        ),
    ]
