# Generated by Django 5.0.7 on 2024-08-04 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Обновлено время')),
                ('is_active', models.BooleanField(blank=True, default=True, null=True, verbose_name='Активен')),
                ('user_id', models.BigIntegerField(null=True, unique=True, verbose_name='ID пользователя (Telegram)')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Имя (Telegram)')),
                ('username', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя пользователя (Telegram)')),
                ('is_blocked_bot', models.BooleanField(default=False, verbose_name='Блокнул бота')),
                ('is_registered', models.BooleanField(default=False, verbose_name='Зарегистрирован')),
            ],
            options={
                'verbose_name': 'ТГ Профиль',
                'verbose_name_plural': 'ТГ Профили',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Обновлено время')),
                ('is_active', models.BooleanField(blank=True, default=True, null=True, verbose_name='Активен')),
                ('email', models.CharField(max_length=320, null=True, unique=True, verbose_name='Электронная почта')),
                ('full_name', models.CharField(max_length=255, null=True, verbose_name='Ф.И.О.')),
                ('phone_number', models.CharField(max_length=255, null=True, verbose_name='Номер телефона')),
                ('balance', models.BigIntegerField(default=0, null=True, verbose_name='Счет')),
                ('paid', models.BigIntegerField(default=0, null=True, verbose_name='Оплаченная сумма')),
                ('role', models.CharField(choices=[('user', 'Пользователь'), ('staff', 'Персонал'), ('manager', 'Менеджер'), ('admin', 'Администратор'), ('ceo', 'Генеральный директор (CEO)')], default='user', max_length=255, verbose_name='Роль')),
                ('password', models.CharField(max_length=255, verbose_name='Пароль')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.contact', verbose_name='Telegram-аккаунт')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
